### PR TITLE
Fix null reference in XmlCommentsModelFilter

### LINKED ISSUE #100: Null reference in GetCommentIdForProperty()
First, wanted to say that this is a great tool, thanks for putting it out there.

Running 6.0.0-beta9 on RC2, I'm finding some null reference exceptions in GetCommentIdForProperty(). jsonProperty.PropertyInfo() appears to never to get set. Changing null check seems to get things running again.
https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Annotations/XmlCommentsModelFilter.cs

        public void Apply(Schema model, ModelFilterContext context)
        {
            var commentId = XmlCommentsIdHelper.GetCommentIdForType(context.SystemType);
            var typeNode = _xmlNavigator.SelectSingleNode(string.Format(MemberXPath, commentId));

            if (typeNode != null)
            {
                var summaryNode = typeNode.SelectSingleNode(SummaryTag);
                if (summaryNode != null)
                    model.Description = summaryNode.ExtractContent();
            }

            foreach (var entry in model.Properties)
            {
                var jsonProperty = context.JsonObjectContract.Properties[entry.Key];
                //if (jsonProperty == null) continue;
                if (jsonProperty.PropertyInfo() == null) continue;

                ApplyPropertyComments(entry.Value, jsonProperty.PropertyInfo());
            }
        }

applypropertycomments

### PR DESCRIPTION
**Pull request by gewoonrik**
fixes #100

### CODE REVIEW

File: src/Swashbuckle.SwaggerGen/Annotations/XmlCommentsModelFilter.cs [hunk 1]
```diff
@@ -34,7 +34,11 @@ public void Apply(Schema model, ModelFilterContext context)
                 var jsonProperty = context.JsonObjectContract.Properties[entry.Key];
                 if (jsonProperty == null) continue;
 
-                ApplyPropertyComments(entry.Value, jsonProperty.PropertyInfo());
+                var propertyInfo = context.JsonObjectContract.UnderlyingType.GetProperty(jsonProperty.UnderlyingName);
```
Comment (domaindrivendev) [inline src/Swashbuckle.SwaggerGen/Annotations/XmlCommentsModelFilter.cs]: At first glance, it seems the above line could be reduced to:

    var propertyInfo = jsonProperty.PropertyInfo();

Maybe I'm missing something and if so, perhaps a unit test would help make the intention here a  little clearer

**Comment by gewoonrik** [comment]
`jsonProperty.PropertyInfo();` did not compile for me. There is no PropertyInfo method on the JsonProperty object. But maybe I'm missing something?

**Comment by gewoonrik** [comment]
My bad, I first fixed this code in my own project and then copied it back. I didn't know that PropertyInfo was a extension method.
